version: '3'
services:

  app:
    build: .
    restart: unless-stopped
    working_dir: /var/www
    environment:
      PHP_IDE_CONFIG: 'serverName=docker'
      XDEBUG_CONFIG: '172.0.0.1'
    volumes:
      - ./:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local